### PR TITLE
Fix typo in entrypoint script

### PR DESCRIPTION
**Pull request by etiennetremel**
Containers won't run because of this typo.

### CODE REVIEW

**Comment by tianon** [comment]
The `:` is an alias of `true`, and it is included specifically to avoid the problem of not running.

See https://travis-ci.org/docker-library/rabbitmq/jobs/314147474#L1646 for an example of where this image is not only built, but also ran and connected to as a test to verify functionality.

(In other words, I can't reproduce a failure on this section of code.)

**Comment by BlueWizardHat** [comment]
We are getting this error trying to use rabbitmq in AWS:

/usr/local/bin/docker-entrypoint.sh: line 285: :#: command not found

Note the error is only triggered when restricting memory usage with cgroups, otherwise the offending line is not executed and causes no errors.

The problem is that while : is an alias of true :# (with no space between) is not. The lines in question are supposed to be comments, there is no need for the : anyhow.

**Comment by tianon** [comment]
Rather than commenting out the entire `if` statement, I'd prefer to simply add a space between the `:` and the `#` (and it needs to be updated in all of `3.7/docker-entrypoint.sh`, `3.7/alpine/docker-entrypoint.sh`, and `3.7/debian/docker-entrypoint.sh`).

@etiennetremel do you want to make that change, or would you prefer I take over?

**Comment by etiennetremel** [comment]
@tianon fixed, could you double check?

**Comment by tianon** [comment]
(going to merge as soon as Travis is happy)

**Pull request merged**
