### PR TITLE
Add "gosu" and step down from root ourselves

### LINKED ISSUE #14: 3.5.0 broken — exited immediately
1) docker run rabbitmq:3.5.0 

Server not started, container exited immediately.

2) docker run rabbitmq:3.4.4

Server started, works as expected.

### PR DESCRIPTION
**Pull request by tianon**
Fixes #14

### CODE REVIEW

**Comment by tianon** [comment]
The money shot for fixing #14 is in:
```Dockerfile
# /usr/sbin/rabbitmq-server has some irritating behavior, and only exists to "su - rabbitmq /usr/lib/rabbitmq/bin/rabbitmq-server ..."
ENV PATH /usr/lib/rabbitmq/bin:$PATH
```

(but means that we need `gosu` since `/usr/sbin/rabbitmq-server` uses `su` to do the same thing)

**Comment by yosifkit** [comment]
Gosu 1.3 :birthday:, everything's shiny Cap'n.

LGTM

In case people are wondering how 3.5 broke:
```console
3.4: su rabbitmq -s /bin/sh -c "/usr/lib/rabbitmq/bin/rabbitmq-server"
3.5: exec su ...
```

**Comment by sburnwal** [comment]
@tianon , @yosifkit - I am trying to understand the exact need for gosu in rabitmq docker. I am new to gosu but reading at libgosu.org tells me it is a 2D gaming library. Can you help me understand why we need gosu for rabbitmq ? Thanks in advance!

**Comment by tianon** [comment]
Heh, not "libgosu" -- see https://github.com/tianon/gosu

**Comment by sburnwal** [comment]
Yes I saw it later, thanks for the quick update, appreciate it!

**Pull request merged**
