### PR TITLE
Add arm64v8 since it is now in the rabbitmq apt repo

### LINKED ISSUE #175: support arm64 architecture
I want to build this image on arm64 architecture but I don't find arm64 package in this file http://www.rabbitmq.com/debian/dists/testing/InRelease , So I want to know this image whether or not support arm64 architecture.

### PR DESCRIPTION
**Pull request by yosifkit**
See architecture list from https://www.rabbitmq.com/debian/dists/testing/Release
```
Architectures: AVR32 alpha amd64 arm armel armhf arm64 hppa hurd-i386 i386 ia64 kfreebsd-amd64 kfreebsd-i386 m32 m68k mips mipsel netbsd-alpha netbsd-i386 powerpc s390 s390x sh sparc
```

```diff
diff --git a/dev/fd/63 b/dev/fd/62
--- a/dev/fd/63
+++ b/dev/fd/62
@@ -5,12 +5,12 @@ Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
 GitRepo: https://github.com/docker-library/rabbitmq.git
 
 Tags: 3.6.11, 3.6, 3, latest
-Architectures: amd64, arm32v5, arm32v7, i386, s390x
+Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, s390x
 GitCommit: 7d76799247764423a69438f72961ef0581788e07
 Directory: 3.6/debian
 
 Tags: 3.6.11-management, 3.6-management, 3-management, management
-Architectures: amd64, arm32v5, arm32v7, i386, s390x
+Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, s390x
 GitCommit: 79277042564875d55e4b05a60c65b6eb46651a94
 Directory: 3.6/debian/management
```

Fixes #175

### CODE REVIEW

**Comment by yosifkit** [comment]
I did build and run on our arm64 build server and it did run without issue.

**Comment by tianon** [comment]
:tada:

**Comment by longquan7** [comment]
@tianon This image is support arm64 and PR merged,but I am not found this in image on https://hub.docker.com/u/arm64v8/

**Comment by tianon** [comment]
Sorry, there was a building glitch -- it's up now: https://hub.docker.com/r/arm64v8/rabbitmq/

**Comment by longquan7** [comment]
@tianon OK,thanks

**Pull request merged**
