### PR TITLE
Remove 3.7

### PR DESCRIPTION
**Pull request by tianon**
> 3.7 goes out of any kind of support on October 1st. There will be one more security patch release of 3.7.x, after that, we can basically assume the 3.7 flavour of this image won't have any upstream releases to benefit from.

> Honestly, the attack 3.7.28 will address is local, requires elevated privileges and is Windows-specific. So this image isn't really affected.

- @michaelklishin, https://github.com/docker-library/rabbitmq/pull/430#issuecomment-674154350

### CODE REVIEW

**Comment by michaelklishin** [comment]
@tianon if we wait for `3.7.28` to be produced and published, we'd have likely the last 3.7 release up on Docker Hub. Then we can merge this.

**Comment by michaelklishin** [comment]
A version with [`3.7.28` has been published](https://github.com/docker-library/rabbitmq/commit/7257ddb5361d42bc5a952b6d2e357fc623131627). Should we merge this @tianon @gerhard?

**Comment by tianon** [comment]
Once we get https://github.com/docker-library/official-images/pull/8568 merged, I'll rebase and merge :+1:

**Comment by tianon** [comment]
(Unless @gerhard objects to removing 3.7 before then -- we can always bring it back again if we need to)

**Comment by gerhard** [comment]
No objections @tianon.

[RabbitMQ release series 3.7 reached end of General Support on 31 March 2020](https://www.rabbitmq.com/versions.html), which is what open source users care about, including the overwhelming majority of this Docker image.

With 3.7.28 out & merged, it's a good time to stop supporting 3.7 in this Docker image.

**Comment by tianon** [comment]
Ok, rebased, green, all is well.  Let's do this. :smile:

**Pull request merged**
