### PR TITLE
Added RABBITMQ_CLUSTER_NODES option in docker-entrypoint.sh to allow …

### PR DESCRIPTION
**Pull request by stachdude**
clustering with a docker environment option

```
-e RABBITMQ_CLUSTER_NODES="{['rabbit@<hostname1.some.domain>', 'rabbit@<hostname2.some.domain>', 'rabbit@<hostnameN.some.domain>', disc}"
```

or for ram node

```
-e RABBITMQ_CLUSTER_NODES="{['rabbit@<hostname1.some.domain>', 'rabbit@<hostname2.some.domain>', 'rabbit@<hostnameN.some.domain>', ram}"
```

### CODE REVIEW

**Comment by pugnascotia** [comment]
FYI, there's still a comment at the bottom of the file about not handling clustering in the script.

**Comment by jippi** [comment]
Any love for this PR ? :)

**Comment by guenhter** [comment]
docker-entrypoint.sh
```
...
	# More ENV vars for make clustering happiness
	# we don't handle clustering in this script, but these args should ensure
...
```

but why? clustering as @stachdude added it would be great!

**Comment by guenhter** [comment]
This tackles #38

**Comment by tianon** [comment]
See also https://github.com/docker-library/docs/pull/1011, which documents a more general-purpose method of providing custom additional configuration.

**Comment by tianon** [comment]
Closing given that this is much easier to accomplish correctly on RabbitMQ 3.7 with the new sysctl-style configuration file format. :+1:

**Pull request closed without merging**
