### PR TITLE
Use environment variable to config file mapping

### PR DESCRIPTION
**Pull request by ejsmith**
I wanted to submit a more complete pull request, but it is sooo hard to understand everything that is going on in this script that I wasn't confident enough to convert everything to use the new config map. It seems like the approach I'm taking here is a LOT more intuitive and allows any config setting to be mapped from an environment variable. Is this something that you would be interested in doing completely and trying to completely convert to this style? I think it would also end up simplifying this script a lot.

### CODE REVIEW

**Comment by tianon** [comment]
Honestly would rather go the other direction and suggest that users who
need configuration should provide a configuration file (the new format in
3.7 is very easy to use and understand).

I'd love to deprecate more of the variables we support and make this script
much shorter (if not make it outright go away).  Maintaining such a delta
above upstream is not great.

**Comment by ejsmith** [comment]
Having to create a new docker image just to set some config entry seems like overkill to me.

**Comment by tianon** [comment]
I suppose the point I'm trying to make is that if it's sane for RabbitMQ to be configured via environment variables, that's something that should happen in RabbitMQ itself instead of us inventing new configuration knobs on top of RabbitMQ that users will then report to them aren't working the way they're "supposed to" (and they don't actually support or really even know about).

Additionally, systems like Docker Swarm and Kubernetes have pretty rich support for supplying configuration files to containers, so I don't think this is necessarily in the realm of something that you'd have to create your own Docker image to support (although with Docker's automated builds, it *is* pretty trivial to create a short image that simply adds a basic configuration file and keep it up to date and actively rebuilt).  It's also not an uncommon thing to have to provide configuration via files (many other software components are configured similarly).

Our primary goal with this image is to provide an authentic RabbitMQ upstream experience (and I think our delta WRT environment variable knobs is one place we're failing at that).

**Comment by michaelklishin** [comment]
I completely agree with @tianon. RabbitMQ should not be configured via env variables besides things that must be set before config file can even be read. This PR moves us in the wrong direction.

**Comment by michaelklishin** [comment]
@ejsmith I see what you are saying. However, providing a config file/path is reasonably straightforward (if not perhaps this image could make it easier somehow) and it makes 100% of today's and tomorrow's configuration settings available to you without any updates on this image's end.
Reinventing config file generation in this image is an uphill battle that we absolutely don't have to fight.

@gerhard would be more qualified than me to suggest a common practice around config files.

**Pull request closed without merging**
