### PR TITLE
Add Alpine variant

### LINKED ISSUE #128: [RFC] add alpine linux
I would like to see an alpine build of rabbitmq.  The changes would be very similar to the ones recently added to the official postgres image.
Ref : https://github.com/docker-library/postgres/issues/214

- Security-focused
- Smaller attack surface
- Smaller image size

### PR DESCRIPTION
**Pull request by tianon**
Closes #128

Thanks to @cavemandaveman for figuring out the last few issues that got me stuck! (https://github.com/infosiftr/rabbitmq/issues/1) :heart:

### CODE REVIEW

**Comment by tianon** [comment]
Ah shoot, this was still WIP so I didn't update `update.sh` or `generate-stackbrew-library.sh` yet. :innocent:

**Comment by tianon** [comment]
And Travis.

**Comment by tianon** [comment]
```console
# this file is generated via https://github.com/docker-library/rabbitmq/blob/74a9d28d4882360eab74a1b9d78ec67143cef345/generate-stackbrew-library.sh

Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
             Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/rabbitmq.git

Tags: 3.6.6, 3.6, 3, latest
GitCommit: 366975d8089b28fb2a58054835f80e1a74328d05
Directory: debian

Tags: 3.6.6-management, 3.6-management, 3-management, management
GitCommit: 366975d8089b28fb2a58054835f80e1a74328d05
Directory: debian/management

Tags: 3.6.6-alpine, 3.6-alpine, 3-alpine, alpine
GitCommit: 13c638644ab9441beb67fd3fef4a60ca532bfb47
Directory: alpine

Tags: 3.6.6-management-alpine, 3.6-management-alpine, 3-management-alpine, management-alpine
GitCommit: 74a9d28d4882360eab74a1b9d78ec67143cef345
Directory: alpine/management
```

**Comment by tianon** [comment]
It's a shame we don't have https://github.com/docker-library/official-images/issues/609 knocked out yet. :smile:

**Comment by cavemandaveman** [comment]
I also noticed that the `docker-entrypoint.sh` that goes with this Dockerfile does not include the changes from #112; might want to update that as well

**Comment by tianon** [comment]
Hah, thanks again @cavemandaveman! :heart:

Updated now!

**Comment by cavemandaveman** [comment]
No problem! Excited to get this on Alpine!

**Pull request merged**
