### PR TITLE
Support for MQTT plugin 

### PR DESCRIPTION
**Pull request by robertobarreda**
Rabbit docker image with management and mqtt enabled #44

### CODE REVIEW

**Comment by JoshBroomberg** [comment]
@robertobarreda what happened with this?

**Comment by robertobarreda** [comment]
@JoshBroomberg no oficial response.
I ended up using my own Dockerfile (the same as in the PR) and including my rabbitmq.config

**Comment by JoshBroomberg** [comment]
Thanks, @robertobarreda. Makes sense. We have used the same approach.

**Comment by yosifkit** [comment]
Sorry for letting this one go without a reply for so long :bowing_man:

> with 3.7's simpler config format, we'd rather move to doing less config via the entrypoint
>
> \- https://github.com/docker-library/rabbitmq/pull/202#issuecomment-337414006

**Pull request closed without merging**
