### PR TITLE
Allow for custom definitions file

### PR DESCRIPTION
**Pull request by cavemandaveman**
If a user mounts a definitions file to /etc/rabbitmq/definitons.json, then it will get loaded on startup. Takes care #107

### CODE REVIEW

**Comment by jippi** [comment]
Any love for this PR ? :)

**Comment by SamYaple** [comment]
Would love to see some progress on this as well. With this, there is no reason to create users or vhosts in the scripts since the definitions file can contain all of this info. Would love to see this merge.

Alternatively, would love to see some way to extend the config with custom code in which case we can use the official image and use the definitions files like that.

**Comment by tianon** [comment]
@michaelklishin or @dumbbell, do you have any thoughts on this? (especially WRT whether it's reasonable to include by default, and whether the filename/path we're adding here as the default is a sane one?)

Would it be better to have something like a `RABBITMQ_MANAGEMENT_DEFINITIONS_FILE` environment variable to make a request for this explicit, or is the presence of the file in a (hopefully well-documented) location fine/sufficient?

**Comment by michaelklishin** [comment]
@tianon definitions are merged with what's already there and empty definitions should do no harm. However, not everything should be configured via definitions. Dynamic Shovels and other things that need to be started when a plugin is loaded will run into race conditions between definition loading and plugin startup, for example.

Users, vhosts, permissions, possibly even topologies can be defined via definitions.

I have a feeling that definitions will be extracted into a separate plugin or moved into the core because right now they are an afterthought in the management plugin (an alternative way of loading definitions that uses a local file system). It's not necessarily going to be a breaking change but I wouldn't say that this feature should be widely advertised and recommended to everyone.
It also means that I'd rename the file to `/etc/rabbitmq/definitions.json`.

**Comment by michaelklishin** [comment]
@cavemandaveman may I ask you to change the default path per my comment above? @tianon I don't have any other suggestions because this feature is opt-in.

**Comment by tianon** [comment]
@michaelklishin thanks for your thoughts! The path you suggest is actually what was originally proposed and I screwed it up before pinging you :disappointed:

I'll update this later today and merge it. :+1:

**Comment by cavemandaveman** [comment]
@tianon Since you made a couple of other tweaks to the PR, I'll leave it up to you to change it.

**Comment by tianon** [comment]
I've swapped it back to the original filename in 3ba4ec4, and added a link to @michaelklishin's comment above for our future selves to reference back to more easily. :sweat_smile:

**Comment by RyanSMurphyDMCo** [comment]
So how do we actually use this? It doesn't seem obvious to me. Do we have to have a particular version of the image? Is it an environment variable, a file put in the right place, named specifically?

**Comment by RyanSMurphyDMCo** [comment]
Tried on both 3.6.6 and 3.7.3. 

It works on 3.7.3, but does not work on 3.6.6.

**Comment by matthewreimer** [comment]
> @tianon definitions are merged with what's already there and empty definitions should do no harm. However, not everything should be configured via definitions. Dynamic Shovels and other things that need to be started when a plugin is loaded will run into race conditions between definition loading and plugin startup, for example.
> 
> Users, vhosts, permissions, possibly even topologies can be defined via definitions.
> 
> I have a feeling that definitions will be extracted into a separate plugin or moved into the core because right now they are an afterthought in the management plugin (an alternative way of loading definitions that uses a local file system). It's not necessarily going to be a breaking change but I wouldn't say that this feature should be widely advertised and recommended to everyone.
> It also means that I'd rename the file to `/etc/rabbitmq/definitions.json`.



> @tianon definitions are merged with what's already there and empty definitions should do no harm. However, not everything should be configured via definitions. Dynamic Shovels and other things that need to be started when a plugin is loaded will run into race conditions between definition loading and plugin startup, for example.
> 
> Users, vhosts, permissions, possibly even topologies can be defined via definitions.
> 
> I have a feeling that definitions will be extracted into a separate plugin or moved into the core because right now they are an afterthought in the management plugin (an alternative way of loading definitions that uses a local file system). It's not necessarily going to be a breaking change but I wouldn't say that this feature should be widely advertised and recommended to everyone.
> It also means that I'd rename the file to `/etc/rabbitmq/definitions.json`.

It appears this has been done in https://github.com/rabbitmq/rabbitmq-management/issues/749.

**Comment by yosifkit** [comment]
Moving the export/import to core, rather than a plugin, is in [3.8.2](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.2) (see CLI Tools -> Enhancements).  Is there something we need to change in the image?

**Comment by matthewreimer** [comment]
I'm not sure. Maybe now definitions.json can contain e.g. shovel definitions with causing a crash, without any change to the image, but I haven't had a chance to test yet.

**Pull request merged**
