### PR TITLE
Use conf.d to enable console logging in RMQ 3.9+

### LINKED ISSUE #554: Do not use RABBITMQ_LOGS to configure logging
TL;DR a configuration file should be used instead in `/etc/rabbitmq/conf.d` to set defaults.

Full discussion here:

https://github.com/rabbitmq/rabbitmq-server/issues/4303

cc @gerhard @mkuratczyk in case one of you remembers why `RABBITMQ_LOGS=-` was chosen. Thanks!

### PR DESCRIPTION
**Pull request by lukebakken**
This replaces the `RABBITMQ_LOGS=-` env variable.

Fixes #554

Test procedure is documented here:

https://github.com/lukebakken/test-docker-library-rabbitmq-gh-554

### CODE REVIEW

**Comment by michaelklishin** [comment]
I tested an image built from this branch and logging works as expected,

**Comment by michaelklishin** [comment]
@lukebakken has an example repo with some instructions: https://github.com/lukebakken/test-docker-library-rabbitmq-gh-554

**Comment by tianon** [comment]
Do you think it'd be reasonable for us to combine these two config files into a `00-docker-defaults.conf` or even  `10-docker-defaults.conf` (so users can inject either before or after without too much hassle), or do you think having these separate like this is better?

**Comment by lukebakken** [comment]
@tianon great question. I only added a new file because of the comment in the existing one:

https://github.com/docker-library/rabbitmq/blob/master/10-default-guest-user.conf#L1-L3

I'll modify the PR to combine the files into `10-defaults.conf`. I will add a note about `log.console` being necessary if you want to see logs the "usual" way in a container.

**Comment by michaelklishin** [comment]
I like the idea of combining them. Why would anyone add a file before these defaults, though? Aren't defaults meant to be overridden? ;) anyhow, `10-defaults.conf` SGTM.

**Comment by lukebakken** [comment]
@tianon thanks for your quick reviews.

**Comment by lukebakken** [comment]
I just read through #506 and this PR does not seem to introduce a situation like the one described there, thankfully.

**Review by yosifkit — APPROVED** [review]

**Comment by michaelklishin** [comment]
@tianon is there anything else we should do to get this in? :)

**Comment by tianon** [comment]
Sorry, just patience :see_no_evil: 

Thanks! :heart:

**Pull request merged**
