### PR TITLE
Build RabbitMQ 3.8 beta releases

### PR DESCRIPTION
**Pull request by gerhard**
> This should be merged after #301 . Will likely require a `master` rebase before.

RabbitMQ 3.8 ships a new queue type, the quorum queue. This queue type
is nothing short of amazing, find out more about it here:
https://youtu.be/YxFCUQ2CndA?t=560

There are a few more exciting RabbitMQ features waiting to be
discovered, use this Docker image tag to see what they are ; )

### CODE REVIEW

**Comment by gerhard** [comment]
Ping @mkuratczyk

**Comment by yosifkit** [comment]
I'd love to have more frequent updates for pre-release builds, but from the build numbers currently available on [bintray](https://dl.bintray.com/rabbitmq/all-dev/rabbitmq-server/) compared to the ones mentioned here and in #301, it makes me think they are nightly or faster. Unfortunately, the official images process does not support nightly releases (too much churn).

> Unlike a release candidate, continuous integration builds which have a fully automated release cycle based on code commits or a regular schedule are not appropriate.
>
> https://github.com/docker-library/official-images/tree/050d779855220cfc475907b8889793bb9c61d5d6#library-definition-files

Are there less frequent versions, like weekly or monthly, that could be used (and available to re-download in case of base image updates)?

Nightly builds could be a fine candidate for Docker's Automated Builds (with Repository Links), though wouldn't have the same architecture reach.

**Comment by gerhard** [comment]
I don't see why you couldn't trigger image builds on a schedule that is suitable for the official images. The fact that alpha releases are being published constantly doesn't mean that you have to consume them at the rate that they are being produced.

From the perspective of availability, an alpha will always be available when your pipeline runs, while an RC might no longer be available - as we've experienced in the past.

**Comment by gerhard** [comment]
@yosifkit would you be more comfortable if we changed this to build 3.8 beta releases instead of alphas? They are less frequent, and would allow Docker users to try out new 3.8 features before the GA ships.

There is no release candidate for 3.8, only [3.8.0-beta.1](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.0-beta.1)

**Comment by michaelklishin** [comment]
It is true, alphas a produced up to multiple times a day depending on Git repository activity. 3.8.x betas are produced every several weeks (or even months).

**Comment by gerhard** [comment]
@yosifkit what do you think?

**Comment by yosifkit** [comment]
This seems fine. These remote artifacts will stick around in cases where the RabbitMQ image is unchanged but an updated Ubuntu/Alpine base image happens and the rebuild of `rabbitmq` will still complete successfully.

As for the directory name, we use the `-rc` to cover [any* pre-release of the software](https://github.com/docker-library/rabbitmq/blob/8a623bb9420b8bfb1cbad2467abb48db26e7ddbc/update.sh#L22-L28), so that we can be a little less involved in renaming directories when moving `alpha` to `beta` to `rc` since we want the bot to handle the update :smile:.

_*: any is currently `beta|milestone|rc` in the update script_

**Comment by gerhard** [comment]
Excellent! Is there anything else that needs to happen before merging?

**Comment by gerhard** [comment]
Folder renamed to 3.8-rc. Anything else @yosifkit ?

**Comment by tianon** [comment]
Here's a simplified `git diff` from the CLI (since GitHub struggles with displaying diffs like this in a sane way that makes them easy to review :sweat_smile:):

```diff
diff --git a/.travis.yml b/.travis.yml
index b10937e..d36ce1a 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,6 +2,8 @@ language: bash
 services: docker
 
 env:
+  - VERSION=3.8-rc VARIANT=ubuntu
+  - VERSION=3.8-rc VARIANT=alpine
   - VERSION=3.7-rc VARIANT=ubuntu
   - VERSION=3.7-rc VARIANT=alpine
   - VERSION=3.7 VARIANT=ubuntu
diff --git a/3.7-rc/alpine/Dockerfile b/3.8-rc/alpine/Dockerfile
similarity index 99%
copy from 3.7-rc/alpine/Dockerfile
copy to 3.8-rc/alpine/Dockerfile
index 4419a2b..c34c8cf 100644
--- a/3.7-rc/alpine/Dockerfile
+++ b/3.8-rc/alpine/Dockerfile
@@ -161,7 +161,7 @@ RUN set -eux; \
 	ln -sf "$RABBITMQ_DATA_DIR/.erlang.cookie" /root/.erlang.cookie
 
 # Use the latest stable RabbitMQ release (https://www.rabbitmq.com/download.html)
-ENV RABBITMQ_VERSION 3.7.11-rc.2
+ENV RABBITMQ_VERSION 3.8.0-beta.1
 # https://www.rabbitmq.com/signatures.html#importing-gpg
 ENV RABBITMQ_PGP_KEY_ID="0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
 ENV RABBITMQ_HOME=/opt/rabbitmq
diff --git a/3.7-rc/alpine/docker-entrypoint.sh b/3.8-rc/alpine/docker-entrypoint.sh
similarity index 100%
copy from 3.7-rc/alpine/docker-entrypoint.sh
copy to 3.8-rc/alpine/docker-entrypoint.sh
diff --git a/3.7/alpine/management/Dockerfile b/3.8-rc/alpine/management/Dockerfile
similarity index 96%
copy from 3.7/alpine/management/Dockerfile
copy to 3.8-rc/alpine/management/Dockerfile
index 89b73d3..810cb10 100644
--- a/3.7/alpine/management/Dockerfile
+++ b/3.8-rc/alpine/management/Dockerfile
@@ -1,4 +1,4 @@
-FROM rabbitmq:3.7-alpine
+FROM rabbitmq:3.8-rc-alpine
 
 RUN rabbitmq-plugins enable --offline rabbitmq_management
 
diff --git a/3.7-rc/ubuntu/Dockerfile b/3.8-rc/ubuntu/Dockerfile
similarity index 99%
copy from 3.7-rc/ubuntu/Dockerfile
copy to 3.8-rc/ubuntu/Dockerfile
index df91308..7d1c5d0 100644
--- a/3.7-rc/ubuntu/Dockerfile
+++ b/3.8-rc/ubuntu/Dockerfile
@@ -169,7 +169,7 @@ RUN set -eux; \
 	ln -sf "$RABBITMQ_DATA_DIR/.erlang.cookie" /root/.erlang.cookie
 
 # Use the latest stable RabbitMQ release (https://www.rabbitmq.com/download.html)
-ENV RABBITMQ_VERSION 3.7.11-rc.2
+ENV RABBITMQ_VERSION 3.8.0-beta.1
 # https://www.rabbitmq.com/signatures.html#importing-gpg
 ENV RABBITMQ_PGP_KEY_ID="0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
 ENV RABBITMQ_HOME=/opt/rabbitmq
diff --git a/3.7-rc/ubuntu/docker-entrypoint.sh b/3.8-rc/ubuntu/docker-entrypoint.sh
similarity index 100%
copy from 3.7-rc/ubuntu/docker-entrypoint.sh
copy to 3.8-rc/ubuntu/docker-entrypoint.sh
diff --git a/3.7/ubuntu/management/Dockerfile b/3.8-rc/ubuntu/management/Dockerfile
similarity index 97%
copy from 3.7/ubuntu/management/Dockerfile
copy to 3.8-rc/ubuntu/management/Dockerfile
index 759f48e..fb5ab76 100644
--- a/3.7/ubuntu/management/Dockerfile
+++ b/3.8-rc/ubuntu/management/Dockerfile
@@ -1,4 +1,4 @@
-FROM rabbitmq:3.7
+FROM rabbitmq:3.8-rc
 
 RUN rabbitmq-plugins enable --offline rabbitmq_management
 
```

**Comment by michaelklishin** [comment]
`3.8.0-beta.2` is now a published release on GitHub

**Comment by yosifkit** [comment]
Triggered the update bot and it seems we have a bug in `update.sh`. tracking it down now.

**Comment by yosifkit** [comment]
And fixed in https://github.com/docker-library/rabbitmq/commit/962e6663ea11698be00c53f2eeb0da40f5551647; bot in progress.

**Pull request merged**
