### PR TITLE
Add 3.13.0-beta.2

### PR DESCRIPTION
**Pull request by tianon**
https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.13.0-beta.2

### CODE REVIEW

**Comment by tianon** [comment]
Oh hmm, those notes say "This release requires Erlang 25.0 or later." near the top, but then later "Starting with this release, RabbitMQ requires Erlang 26.0 or later versions."

I guess we should update to 26 here (and those notes probably updated). :sweat_smile:

**Comment by michaelklishin** [comment]
Thank you! I was about to open an issue requesting a 3.13 preview :)

Yes, 3.13 will require 26 even though it does not right now. Let's move to Erlang 26 for 3.13.

**Comment by tianon** [comment]
Hmm, the build looks good, but our `rabbitmq-tls` test is failing (https://github.com/docker-library/official-images/tree/master/test/tests/rabbitmq-tls); not sure exactly why yet. :sob:

(it looks like it's never getting past `rabbitmq-diagnostics check_port_connectivity` :disappointed:)

**Comment by michaelklishin** [comment]
@tianon Erlang 26 breaks TLS by changing some defaults. Namely, peer verification is now on by default. We disabled it by default in RabbitMQ's own test suites.

**Comment by lukebakken** [comment]
I'm looking into the TLS failure now.

**Comment by lukebakken** [comment]
@tianon this PR _might_ address the issue, but I have no idea the best way to test it -

https://github.com/docker-library/official-images/pull/14951

**Comment by lukebakken** [comment]
Related issue - https://github.com/erlang/otp/issues/7497

**Comment by yosifkit** [comment]
That is amazing. 🎉 Thanks so much @lukebakken for digging into the failure and finding where the bug is! ❤️❤️❤️

**Comment by lukebakken** [comment]
https://github.com/docker-library/official-images/pull/14951 should fix the `check_port_connectivity` issue, and then this PR should be good-to-go.

**Comment by tianon** [comment]
Updated to 3.13.0-beta.2, https://github.com/docker-library/official-images/pull/14951 is in, hopefully this should be good to go now! :crossed_fingers:

**Pull request merged**
