### PR TITLE
Update to 3.13.0 (GA)

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Oh, we should probably remove 3.9 through 3.11 also, as they're all EOL as far as I understand?

**Comment by tianon** [comment]
(That's really orthogonal to getting 3.13 out though)

**Review by yosifkit — APPROVED** [review]

**Comment by michaelklishin** [comment]
Yes, no longer building the series older than 3.12 makes sense. They are out of community support or even have reached EOL.

**Comment by tianon** [comment]
Nice, thanks for confirming :bow: :heart: :+1:

**Pull request merged**
