### PR TITLE
Add "procps" back for "rabbitmqctl wait"

### PR DESCRIPTION
**Pull request by tianon**
Thanks @bfink13!

(This is a redo of #163, fixing #162, as pointed out in https://github.com/docker-library/rabbitmq/pull/297#issuecomment-460392847)

### CODE REVIEW

**Comment by bfink13** [comment]
Thanks for the super fast turnaround! Is the push to docker hub done automatically or manually on a schedule or what?

**Comment by tianon** [comment]
https://github.com/docker-library/rabbitmq#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet :wink:

**Comment by gerhard** [comment]
[`rabbitmqctl wait` relies on `ps -p`](https://github.com/rabbitmq/rabbitmq-common/blob/v3.7.11/src/rabbit_misc.erl#L1032)

In Ubuntu, this command works out of the box:

```
docker run --rm ubuntu:18.04 ps -p 1
  PID TTY          TIME CMD
    1 ?        00:00:00 ps
```

In Alpine, it doesn't:

```
docker run --rm alpine:3.8 ps -p 1
ps: unrecognized option: p
BusyBox v1.28.4 (2018-12-31 18:05:13 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
```

Alpine with `procps` installed:

```
docker run --rm alpine:3.8 sh -c "apk add procps && ps -p 1"
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/6) Installing libintl (0.19.8.1-r2)
(2/6) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(3/6) Installing ncurses-terminfo (6.1_p20180818-r1)
(4/6) Installing ncurses-libs (6.1_p20180818-r1)
(5/6) Installing libproc (3.3.15-r0)
(6/6) Installing procps (3.3.15-r0)
Executing busybox-1.28.4-r3.trigger
OK: 12 MiB in 19 packages
  PID TTY          TIME CMD
    1 ?        00:00:00 ps
```

I propose we revert ff74887d5e4594e1acf80cc6c0eb3915627abe73 and add `procps` to Alpine only.

**Comment by tianon** [comment]
Doh, sounds good!

**Pull request merged**
