### PR TITLE
Add healthcheck

### PR DESCRIPTION
**Pull request by gerhard**
RabbitMQ healthchecks are hard, as captured by @michaelklishin in
https://github.com/docker-library/rabbitmq/pull/174#issuecomment-452002696
and followed-up in rabbitmq/rabbitmq-cli#292

This is an attempt to simplify the inherent complexity by taking the
first step in what will likely become a new rabbitmqctl diagnostics
command. To follow-up on this idea, join rabbitmq/rabbitmq-cli#292.

Things that we might want to discuss:

* is 30s a reasonable amount to wait before starting a RabbitMQ node for healthines?
* should we account for nodes that can take a long time to boot?
* should we retry longer before considering the node unhealthy?
* is 3s a reasonable command timeout?
* should we improve the active listeners check?

Superceeds docker-library/rabbitmq#174
Related to docker-library/docs#1395

I've based this on PR #297 since the current debian image won't `docker build` due to openssl failures, as captured by the CI.

### CODE REVIEW

**Comment by yosifkit** [comment]
Since there isn't a "one-size-fits-all" check, I'd still rather stick to documenting possible options instead of forcing one on everybody.

See also https://github.com/docker-library/faq#healthcheck.

**Comment by gerhard** [comment]
While some users might want a more comprehensive check, a coarse default which will be accurate in all except edge cases is better than no healthcheck.

Having read the Healthcheck FAQ, I understand the reasoning and will play within the constraints of the ecosystem.

@yosifkit is it worth contributing the rationale from this PR into https://github.com/docker-library/docs/tree/master/rabbitmq ?

**Comment by michaelklishin** [comment]
FWIW RabbitMQ CLI tools are [being extended](https://github.com/rabbitmq/rabbitmq-cli/issues/292) to make a [number of health checks](http://www.rabbitmq.com/monitoring.html) to be one liners or a combination of a few one liners. Then Docker and Kubernetes users would be able to pick the "stage" they want and easily use it as their healthcheck/liveness probe.

**Comment by michaelklishin** [comment]
All but one of the new health check commands (see `rabbitmq-diagnostics --help`) will be available as of RabbitMQ `3.7.11`.

**Comment by michaelklishin** [comment]
Worth mentioning here: Kubernetes seems to be [moving past](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0007-pod-ready%2B%2B.md) the One True Health Check™ idea and towards a list of both generic and system-specific checks.

**Pull request closed without merging**
