### PR TITLE
Add rabbitmq-clusterer support

### PR DESCRIPTION
**Pull request by SamYaple**
rabbitmq-clusterer is a plugin created and maintained by the RabbitMQ
team to help facilitate clustering. It will automatically cluster nodes
without the need for the typical "stop_app, join_cluster, start_app"
dance. It can also start a cluster up from a completely stopped start
with no user intervention.

### CODE REVIEW

**Comment by SamYaple** [comment]
I've made this PR to talk about clustering and possibly script extension. I understand this repo cannot be responsible for every conceivable plugin combination and respect that. However, there is a noticeable lack of clustering ability from the official rabbitmq image. I think clusterer can solve this problem.

I have been using rabbitmq-clusterer in docker in the Kolla project for over a year now. It works extremely well in containers. I have pushed this change to DockerHub in a different image which can be viewed [https://hub.docker.com/r/samyaple/rabbitmq-clusterer/](here).

It shows how easy it _can_ be to setup clustered rabbitmq. I would love to see this merge in some form, but really my goal is to show that there is a strong need for config customization. With proper config customization I would not need to duplicate the entire docker-entrypoint.sh like I do [https://github.com/SamYaple/rabbitmq-clusterer/blob/master/docker-entrypoint.sh](here)

That said, I did spend a bit of time making this patch match the coding style already present in the official image, so I feel there may be a path forward to merge this in some form.

A quote from that page:

For a two node cluster, run:

docker run \
-e RABBITMQ_ERLANG_COOKIE=12345 \
-e RABBITMQ_CLUSTERER_NODE_1="rabbtest,disc" \
-e RABBITMQ_CLUSTERER_NODE_2="rabbtest2,disc" \
-e RABBITMQ_CLUSTERER_GOSPEL_NODE="rabbtest" \
--hostname rabbtest \
--name rabbtest \
-d samyaple/rabbitmq-clusterer

docker run \
-e RABBITMQ_ERLANG_COOKIE=12345 \
-e RABBITMQ_CLUSTERER_NODE_1="rabbtest,disc" \
-e RABBITMQ_CLUSTERER_NODE_2="rabbtest2,disc" \
-e RABBITMQ_CLUSTERER_GOSPEL_NODE="rabbtest" \
--hostname rabbtest2 \
--name rabbtest2 \
--link rabbtest \
-d samyaple/rabbitmq-clusterer

**Comment by michaelklishin** [comment]
Please bear in mind that as of the future `3.7.0` release, team RabbitMQ considers `rabbitmq-clusterer` to be unnecessary. It won't be abandoned overnight but there hasn't been any new development for a while and it is really unlikely that there will be in the future.

**Comment by SamYaple** [comment]
@michaelklishin yea ive been following 3.7.0 for a long while now. Looking forward too it.

Frankly, I just want a way to extend the entrypoint.sh without an entirely new container. With that, PRs like this and a few others wouldn't be needed and we could all go on using the official images.

**Comment by SamYaple** [comment]
https://github.com/docker-library/rabbitmq/pull/121

**Comment by SamYaple** [comment]
For those that see this, I started just binding in a new entrypoint.sh are run time (as well as the plugin i wanted).

**Pull request closed without merging**
