### PR TITLE
3.9-rc updates

### LINKED ISSUE #466: management image variants does not support rabbitmq plugins packaged as directories
https://github.com/rabbitmq/rabbitmq-server/commit/25f45fc59b0e63b376c7091321c82b38b5c29317 has changed the default for packaging rabbitmq's included plugins - they are no longer compressed files, and instead are expanded directories. This breaks the `-management` images who expect to perform the extraction.

See https://github.com/rabbitmq/rabbitmq-server/pull/2838 for one solution.

### PR DESCRIPTION
**Pull request by yosifkit**
Adjust management images for 3.9: fixes #466
Also combine the management `RUN` lines into a single `RUN`

**Edit:** this also drops the ability to use the Docker-specific environment variable to generate a config in 3.9. Users should instead provide a config file. Here is the location that rabbitmq will look: `/etc/rabbitmq/rabbitmq.conf` (or `.config` for the erlang syntax file).

These are the specific variables that will no longer work:
```console
RABBITMQ_DEFAULT_PASS
RABBITMQ_DEFAULT_PASS_FILE
RABBITMQ_DEFAULT_USER
RABBITMQ_DEFAULT_USER_FILE
RABBITMQ_DEFAULT_VHOST
RABBITMQ_MANAGEMENT_SSL_CACERTFILE
RABBITMQ_MANAGEMENT_SSL_CERTFILE
RABBITMQ_MANAGEMENT_SSL_DEPTH
RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT
RABBITMQ_MANAGEMENT_SSL_KEYFILE
RABBITMQ_MANAGEMENT_SSL_VERIFY
RABBITMQ_SSL_CACERTFILE
RABBITMQ_SSL_CERTFILE
RABBITMQ_SSL_DEPTH
RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT
RABBITMQ_SSL_KEYFILE
RABBITMQ_SSL_VERIFY
RABBITMQ_VM_MEMORY_HIGH_WATERMARK
```

### CODE REVIEW

**Comment by yosifkit** [comment]
This PR should wait until we have a 3.9 (alpha/beta/rc) release to test and be updated to include it.

**Review by tianon — APPROVED** [review]
:eyes:

**Comment by michaelklishin** [comment]
Thank you. We already have alphas of 3.9 but I'd wait until the first beta indeed. How plugins are loaded won't change before it but some other significant PRs are still to be finished and merged first.

**Comment by michaelklishin** [comment]
We will have an 3.9 beta very soon and filed #491 to make sure it can be built/tagged the same way RCs can be already.

**Comment by tianon** [comment]
I've just updated this with today's beta, but as mentioned over in #424, I'd love to resolve that and actually remove the deprecated entrypoint bits here if there's agreement to do so.

**Comment by yosifkit** [comment]
Rebased to pull in https://github.com/docker-library/rabbitmq/pull/424 and https://github.com/docker-library/rabbitmq/pull/492.

So, do we switch this new `3.9` series to drop most of the entrypoint or keep the warnings for `3.9.x` and drop in `3.10` (or `4.0`)?

**Comment by michaelklishin** [comment]
@yosifkit I'd say let's drop for `3.9`.

**Comment by yosifkit** [comment]
Should we have it print and exit out if it gets any of the old variables, just print a warning, or silently ignore them?

**Comment by michaelklishin** [comment]
@yosifkit assuming we have a changelog, we can document the behavior change and ignore them.

**Comment by yosifkit** [comment]
The only "changelog" options we currently have are the commits to this repo or a note to the [Docker Hub page](https://hub.docker.com/_/rabbitmq).

**Comment by tianon** [comment]
IMO our best option here is to hard-code a list of variables that if any are set, we error out with a deprecation notice -- the implementation of that should be pretty trivial (the harder bit is generating the list of variables we need to error out on, but that's not _too_ bad).  Then in 3.9 + 1 (3.10?) we can remove completely?  (or even just after a suitable amount of time / number of patch releases)

**Comment by yosifkit** [comment]
Is https://github.com/docker-library/official-images/pull/10425 similar to the expected setup users will need in order to use rabbitmq with TLS without our env vars?

Obviously, they should better manage the ssl keys via secrets/config maps and not build them into an image.

**Comment by michaelklishin** [comment]
@edbyford @Zerpet this is the PR that should enable Docker image builds of 3.9 previews.

**Comment by michaelklishin** [comment]
@tianon I agree that hardcoding a list of known variables that are now deprecated would be the pragmatic thing to do.

**Comment by michaelklishin** [comment]
@yosifkit that test change looks reasonable. I'll leave it to @zerpet @ansd and @gerhard to provide any container best practices but they will have to mount/generate/produce from secrets some key/value files, and specify their paths in `rabbitmq.conf`.

For inter-node communication, using a [separate file](https://rabbitmq.com/clustering-ssl.html#strategy-two-flags) in the classic config format is what we usually recommend but what the tests above do is acceptable.

**Comment by Zerpet** [comment]
> Is docker-library/official-images#10425 similar to the expected setup users will need in order to use rabbitmq with TLS without our env vars?

Yes, that's right. Agreed that the best way to get the certificates inside the container would be via Docker/Kubernetes secrets. For local development, it should be possible to generate the certificates locally and mount the directory inside the container.

> Can our test be simplified or improved in some way?

I can't think of anything to simplify the tests, they look good to me.

**Comment by yosifkit** [comment]
Latest commit adds a check to the `3.9-rc` entrypoint to print errors and then exit if any old environment values are found. In a later release it will be adjusted to just print a warning and eventually not even check.

This does seem a bit backwards from a usual deprecation but I think this will be more likely to be noticed (a flapping container) versus having unapplied config and the symptom of being unable to connect.

**Comment by michaelklishin** [comment]
@yosifkit thank you, that is a firm guidance in the right direction but I think it's appropriate. I'd change the wording a bit to make it say something like "please use a configuration file instead, visit https://www.rabbitmq.com/configure.html to learn more". A doc guide link should greatly help folks learn about the recommended option.

I'd also be happy to produce an "equivalence table" of sorts for the env variables we deprecate and the `rabbitmq.conf` (or `advanced.config`) settings that do the same thing. We then can put it into the change log.

**Comment by tianon** [comment]
Makes sense (I've updated the PR accordingly)!

The conversion matrix is pretty straightforward:

- `RABBITMQ_DEFAULT_PASS`: `default_pass`
- `RABBITMQ_DEFAULT_USER`: `default_user`
- `RABBITMQ_DEFAULT_VHOST`: `default_vhost`
- `RABBITMQ_MANAGEMENT_SSL_CACERTFILE`: `management.ssl.cacertfile`
- `RABBITMQ_MANAGEMENT_SSL_CERTFILE`: `management.ssl.certfile`
- `RABBITMQ_MANAGEMENT_SSL_DEPTH`: `management.ssl.depth`
- `RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT`: `management.ssl.fail_if_no_peer_cert`
- `RABBITMQ_MANAGEMENT_SSL_KEYFILE`: `management.ssl.keyfile`
- `RABBITMQ_MANAGEMENT_SSL_VERIFY`: `management.ssl.verify`
- `RABBITMQ_SSL_CACERTFILE`: `ssl_options.cacertfile`
- `RABBITMQ_SSL_CERTFILE`: `ssl_options.certfile`
- `RABBITMQ_SSL_DEPTH`: `ssl_options.depth`
- `RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT`: `ssl_options.fail_if_no_peer_cert`
- `RABBITMQ_SSL_KEYFILE`: `ssl_options.keyfile`
- `RABBITMQ_SSL_VERIFY`: `ssl_options.verify`
- `RABBITMQ_VM_MEMORY_HIGH_WATERMARK`: `vm_memory_high_watermark.*`

**Review by michaelklishin — APPROVED** [review]

**Comment by tianon** [comment]
Thanks @michaelklishin :+1:

I've rebased for hopefully the last time before merge! :smile:

**Comment by gerhard** [comment]
[3.9.0-rc.1 shipped on a Friday, as expected](https://github.com/rabbitmq/rabbitmq-server/discussions/3184) 😎

I'm wondering if we will be able to share the Docker version - `rabbitmq:3.9-rc` - at [RabbitMQ Summit 2021](https://rabbitmqsummit.com/)

Happy weekend everyone 🙌🏻

**Comment by yosifkit** [comment]
Triggered the update bot and then opened the PR to official images: https://github.com/docker-library/official-images/pull/10514.  Should be able to merge it soon.

**Comment by gerhard** [comment]
Thank you for making rc.1 available in time for the RabbitMQ Summit 2021. Even though I can't see how many downloads [this tag had](https://hub.docker.com/layers/rabbitmq/library/rabbitmq/3.9.0-rc.1/images/sha256-378c322916b858fa3ae05a3f4575198aafca22a82c96472a2a74526e6c87d0ee?context=explore), I'm sure it was easy for a few try it out. [I know for a fact](https://github.com/rabbitmq/rabbitmq-server/discussions/3184#discussioncomment-1004700) that @motmot80 gave it a quick check 👍🏻 

[3.9.0-rc.2](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.9.0-rc.2) was made public early today. Any chance we could trigger an rc.2 image? Thanks!

By the way, [this release calendar](https://rabbitmq.com/versions.html#next-release-series) keeps track of what is expected to happen next. Here's a point-in-time snapshot:

image

**Comment by gerhard** [comment]
Thank you!

image

**Pull request merged**
