### PR TITLE
add 3.7.4-rc.1

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by yosifkit** [comment]
Can you put it all in a `3.7-rc` folder rather than the full version like https://github.com/docker-library/rabbitmq/commit/501a83a7b54f4b151e6ad9eae37602b964b1f5d0?  Please run update.sh so that the travis file will be updated to test it.

**Comment by getong** [comment]
There are two tags:
```
2d9ca478b5fec2ad6e3e492771ef7e489b2e71be        refs/tags/v3.7.4-rc.1
41ec73b886a23c80f40960137d8a11de6454e50c        refs/tags/v3.7.4-rc.1^{}
```
So the update.sh need to filter the `\^{}$`.

**Comment by getong** [comment]
The debian dockerfile add apt-utils .

**Comment by tianon** [comment]
> The debian dockerfile adds apt-utils .

Can you elaborate on why?  Does anything actually fail as a result of this package not being included, or is this simply to quiet the (harmless) warning that APT spits out when it's not installed?

**Comment by getong** [comment]
Yesterday, I push this pr and builded failed, with this log msg:
```
delaying package configuration, since apt-utils is not installed
```
So I add apt-utils.


**Comment by getong** [comment]
The keyserver website not found, I only change the 3.7-rc dir, not change the other dir.

**Pull request merged**
