### PR TITLE
Move loopback_users line into main Dockerfile

### LINKED ISSUE #3: Rabbitmq default user will only allow connections from localhost
Rabbitmq does not allow external clients to connect via default user guest except from localhost, in a docker container this doesn't seem like a good set of default user creds. 

From the release notes:
"25603 prevent access using the default guest/guest credentials except via localhost (since 1.0.0)"

Source: http://www.rabbitmq.com/release-notes/README-3.3.0.txt

Would suggest some other default user.

### PR DESCRIPTION
**Pull request by tianon**
Fixes #3

### CODE REVIEW

**Comment by tianon** [comment]
cc @yosifkit @Moghedrin

**Comment by yosifkit** [comment]
LGTM

**Comment by rajnemani** [comment]
Hello,
Can you please help with correct connection string to connect to this container from a nodejs application using amqplib module.  My container is running in Kitematic's Docker VM and my nodejs app is on the host running MAC OS X.  I have passed in the -P flag when starting the container which set the port as 0.0.0.0:32768->5672/tcp.  The connection string I am trying is of the form
amqp://guest:guest@hostName:32768/.  I am unclear what should be the hostName here.  I am also not sure if guest/guest are the right credentials.  Any help is appreciated and thank you in advance.  
Thanks

**Comment by yosifkit** [comment]
@rajnemani you would need the hostname of the docker container.  I think `--hostname my-rabbit` or similar would help but then you'll need to set an `/etc/hosts` entry for the boot2docker ip for that same name.

**Comment by rajnemani** [comment]
@yosifkit Thank you for your help.  I tried this without luck.  Did anybody use this container from a standalone app instead of linking to another docker container?  Any other thoughts.?  I will keep trying in the meantime.  Highly appreciate your time.
Thanks again
Raj

**Pull request merged**
