### PR TITLE
Add support to specify cluster_partition_handling through ENV vars

### PR DESCRIPTION
**Pull request by boeboe**
Used in a Kubernetes context, it is very convenient to be able to specify the cluster partition handling as documented at https://www.rabbitmq.com/partitions.html

Using the RABBITMQ_CLUSTER_PARTITION_HANDLING environment value is a flexible solution.

### CODE REVIEW

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/pull/1011.

**Comment by yosifkit** [comment]
@noteits, I would assume that these changes would work, but I have never used them. We try to keep what the entrypoint uses to a minimal set, which is why this PR is not merged.

One suggestion is using `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS`. Or if you are using `rabbitmq:3.7`, you can use the newer config format: https://www.rabbitmq.com/configure.html#config-file and the file will not be completely overwritten when you provide any of the env vars. So you can provide a base config built into your image with values that are not supported by the entrypoint and then customize it on deployment with the environment variables.

**Comment by noteits** [comment]
Thanks for your explanations, but unfortunately I am using 3.6.14.
I've added this changes to the docker-entrypoint.sh in container and restarted it.
sed -i "68i cluster_partition_handling" docker-entrypoint.sh
sed -i /'verify|fail_if_no_peer_cert|depth)'/d  docker-entrypoint.sh
sed -i "217i verify|fail_if_no_peer_cert|depth|cluster_partition_handling)" docker-entrypoint.sh
Also 
# echo $RABBITMQ_CLUSTER_PARTITION_HANDLING
pause_minority
#
But it's not working. Is any other solution how to add pause_minority to config file? :(

**Comment by yosifkit** [comment]
> with 3.7's simpler config format, we'd rather move to doing less config via the entrypoint
>
> \- https://github.com/docker-library/rabbitmq/pull/202#issuecomment-337414006

**Pull request closed without merging**
