### PR TITLE
Add `4.0.0-beta.1` pre-release

### PR DESCRIPTION
**Pull request by yosifkit**
🎉 A new RabbitMQ release series, `4.0`. Use latest OS releases (Ubuntu 24.04 LTS and Alpine 3.20); bump openssl to 3.3.x, the series used in testing upstream RabbitMQ: https://github.com/docker-library/rabbitmq/issues/712#issuecomment-2231887808

closes https://github.com/docker-library/rabbitmq/issues/712

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Maybe not a huge issue but the version being reported for RabbitMQ here is `3.13.0+424.g256fd8e` not `4.0.0-beta.1`

**Comment by yosifkit** [comment]
That's the version detected by the `syft` SBOM scanner? I would guess that is just because it is a pre-release. But I'm not familiar enough with the RabbitMQ build/release process to know where that gets injected.

**Comment by LaurentGoderre** [comment]
Except for the case of RabbitMQ, these are the versions that are defined explicitly in the packages so it's not a detection issue.

**Comment by yosifkit** [comment]
Yeah, it should be fine. I think it is still accurate and should be correct by the stable release.

I _think_ it could be related to the version in [`MODULE.bazel`](https://github.com/rabbitmq/rabbitmq-server/blob/v4.0.0-beta.1/MODULE.bazel#L3), but I don't really know since there is also a version in [`rabbitmq.bzl`](https://github.com/rabbitmq/rabbitmq-server/blob/v4.0.0-beta.1/rabbitmq.bzl#L40).

**Comment by michaelklishin** [comment]
> Maybe not a huge issue but the version being reported for RabbitMQ here is `3.13.0+424.g256fd8e` not `4.0.0-beta.1`

That has nothing to do with the image. Team RabbitMQ has decided to ship the first beta even like so. It does not prevent anyone from testing what we actually want to see tested. What everyone in the community *needs* tested early and often.

**Comment by michaelklishin** [comment]
@yosifkit setting `PRODUCT_VERSION` when the node is started would override the version. However, this is something that should be addressed in RabbitMQ's own release pipelines. Right now the version of development releases comes from the most recent tag on the `main` branch, even though we no longer produce releases straight off of `main`.

For "final" releases this default does not exist.

**Pull request merged**
