### PR TITLE
Allow custom log_levels

### PR DESCRIPTION
**Pull request by zoidbergwill**
Closes https://github.com/docker-library/rabbitmq/issues/118

### CODE REVIEW

**Comment by zoidbergwill** [comment]
Tested with:

```
docker run -it --rm -e RABBITMQ_LOG_LEVELS='[{connection, error}]' $IMAGE_ID
```

**Comment by tianon** [comment]
So far we've avoided exposing the user to any raw Erlang configuration in any of our environment variables, and especially considering that the 3.6 version of RabbitMQ is moving to a configuration file that's INI-based, I'd like to continue sticking to that.

**Comment by michaelklishin** [comment]
@tianon the Erlang term config format isn't going away, in fact, some things have such as complex structure that I don't think they can be moved to the .ini-style format. In 3.7.0 it will be a separate config file, though, and most things will use the .ini one. JFYI.

**Comment by michaelklishin** [comment]
Config settings can be passed on the command line, e.g.

```
RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbit log_levels [{connection,error}]" rabbitmq-server
```

which is an Erlang/OTP feature: `-rabbit key value` on the command line is the same as setting `rabbit.key` to `value` in the Erlang term config file.

**Comment by michaelklishin** [comment]
@tianon in this particular case, the value of `log_levels` seems to be treated (passed on) as a string, so you don't necessarily run much risk in white listing it.

More complicated cases (e.g. [LDAP queries](http://www.rabbitmq.com/ldap.html)) should be configured by providing a file IMO.

**Comment by tianon** [comment]
Ooooh, we should definitely document `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` -- that way we could stop doing so many of these one-off environment variables! :smile:  Does that mean `-rabbit` could be specified more than once?

ala, `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbit log_levels [{connection,error}] -rabbit something <<'somevalue'>>"` ?

Good to know regarding the ini-style config -- will keep that in mind. :sweat_smile:

**Comment by michaelklishin** [comment]
@tianon no, it would be `-rabbit  key1 value1 key2 value 2`. See [section 8.8 in this Erlang guide](http://erlang.org/doc/design_principles/applications.html).

**Comment by zoidbergwill** [comment]
I guess that makes this PR related to this one as well: https://github.com/docker-library/rabbitmq/issues/138 

😋

**Comment by ilude** [comment]
See Pull request [#187](https://github.com/docker-library/rabbitmq/pull/187)

**Pull request closed without merging**
