### PR TITLE
Add support for enabling "hipe_compile" at runtime

### PR DESCRIPTION
**Pull request by tianon**
Closes #65

### CODE REVIEW

**Comment by tianon** [comment]
(docs in docker-library/docs#476 still apply)

**Comment by tianon** [comment]
Woot, it works! :+1:

```console
$ docker run -it --rm 56460038a1c8

              RabbitMQ 3.6.2. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########

...

$ docker run -it --rm -e RABBITMQ_HIPE_COMPILE=1 56460038a1c8

HiPE compiling:  |---------------------------------------------------------|
                 |#########################################################|

Compiled 57 modules in 19s

=INFO REPORT==== 5-Jul-2016::23:57:11 ===
HiPE in use: compiled 57 modules in 19s.

=INFO REPORT==== 5-Jul-2016::23:57:11 ===
Starting RabbitMQ 3.6.2 on Erlang 18.3
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

              RabbitMQ 3.6.2. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########

...
```

**Comment by yosifkit** [comment]
LGTM

**Comment by michaelarnauts** [comment]
In case somebody gets crazy why rabbitmq keeps compiling: `-e RABBITMQ_HIPE_COMPILE=0` will not work. I repeat. This doesn't work, it will compile it. Just remove the line.

**Pull request merged**
