### PR TITLE
Additional config parameters

### PR DESCRIPTION
**Pull request by xytis**
Would it be logical to add all config parameters described in https://www.rabbitmq.com/configure.html?

Note this PR removes the "<< >>" from var expansion. User is expected to write them himself.
Perhaps I should update the documentation together?

### CODE REVIEW

**Comment by yosifkit** [comment]
I'm not sure we would want to add all of the available config options, since a user could just create and mount a config file at that point.  We do want to ensure that the most common use cases are easy for new users.

I am unsure on whether or not this new one should be added, and if so, should it just be a special case to not print the `<<" ">>` on this new one, or make users add them to the old options?  I am hesitant to make the user add them since this would be a breaking change.

**Comment by xytis** [comment]
Can you explain what do you mean by 'create and mount a config file' ?

**Comment by yosifkit** [comment]
A user may want to setup a custom, oft-used configuration on the host machine and mount it into their container:

```console
docker run -d -v /my/local/copy/rabbit.config:/etc/rabbitmq/rabbitmq.config rabbitmq
```

**Comment by tianon** [comment]
Or build an image that includes the desired configuration built-in already,
and use automated builds and repository links to keep it up to date.

**Pull request closed without merging**
